version: '3.7'
services:
  discord_bot:
    container_name: discord_bot
    image: 3onier/discord_bot
    tty: true
    restart: always
    depends_on:
      - bot_maria_db
    environment:
      TOKEN: "<TOKEN>"
      DB_HOST: ""
      DB_PORT: "3306"
      DB_NAME: "discord_bot"
      DB_USER: ""
      DB_PASSWORD: ""
    volumes:
      - 'data:/bot/data'
  bot_maria_db:
    container_name: bot_maria_db
    image: mariadb:latest
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '<MYSQL root password>'
      MYSQL_DATABASE: 'discord_bot'
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
    volumes:
      - 'database_configs:/etc/mysql/conf.d'
      - 'database_files:/var/lib/mysql'
volumes:
  data: {}
  database_configs: {}
  database_files: {}