version: '3.7'
services:
  discord_bot:
    container_name: discord_bot
    image: 3onier/discord_bot
    tty: true
    restart: always
    environment:
      TOKEN: "<TOKEN>"
      DB_HOST: ""
      DB_PORT: "3306"
      DB_NAME: "discord_bot"
      DB_USER: ""
      DB_PASSWORD: ""
    volumes:
      - 'data:/bot/data'
volumes:
  data: {}